-- Enabling the replication database
use master
exec sp_replicationdboption @dbname = N'scalaDB', @optname = N'publish', @value = N'true'
GO

exec [scalaDB].sys.sp_addlogreader_agent @job_login = null, @job_password = null, @publisher_security_mode = 1
GO
-- Adding the transactional publication
use [scalaDB]
exec sp_addpublication @publication = N'PublicationScalaAM31', @description = N'Transactional publication of database ''scalaDB'' from Publisher ''VM-TLN-SCP01''.', @sync_method = N'concurrent', @retention = 0, @allow_push = N'true', @allow_pull = N'true', @allow_anonymous = N'false', @enabled_for_internet = N'false', @snapshot_in_defaultfolder = N'true', @compress_snapshot = N'false', @ftp_port = 21, @ftp_login = N'anonymous', @allow_subscription_copy = N'false', @add_to_active_directory = N'false', @repl_freq = N'continuous', @status = N'active', @independent_agent = N'true', @immediate_sync = N'false', @allow_sync_tran = N'false', @autogen_sync_procs = N'false', @allow_queued_tran = N'false', @allow_dts = N'false', @replicate_ddl = 1, @allow_initialize_from_backup = N'true', @enabled_for_p2p = N'false', @enabled_for_het_sub = N'false'
GO


exec sp_addpublication_snapshot @publication = N'PublicationScalaAM31', @frequency_type = 1, @frequency_interval = 0, @frequency_relative_interval = 0, @frequency_recurrence_factor = 0, @frequency_subday = 0, @frequency_subday_interval = 0, @active_start_time_of_day = 0, @active_end_time_of_day = 235959, @active_start_date = 0, @active_end_date = 0, @job_login = null, @job_password = null, @publisher_security_mode = 1
exec sp_grant_publication_access @publication = N'PublicationScalaAM31', @login = N'sa'
GO
exec sp_grant_publication_access @publication = N'PublicationScalaAM31', @login = N'NT SERVICE\Winmgmt'
GO
exec sp_grant_publication_access @publication = N'PublicationScalaAM31', @login = N'NT SERVICE\SQLWriter'
GO
exec sp_grant_publication_access @publication = N'PublicationScalaAM31', @login = N'NT SERVICE\SQLSERVERAGENT'
GO
exec sp_grant_publication_access @publication = N'PublicationScalaAM31', @login = N'repl2'
GO
exec sp_grant_publication_access @publication = N'PublicationScalaAM31', @login = N'distributor_admin'
GO

-- Adding the transactional articles
use [scalaDB]  
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM310100',  @source_owner = N'dbo',   @source_object = N'AM310100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM310100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM310100]',   @del_cmd = N'CALL [sp_MSdel_dboAM310100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM310100]'  
GO
use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM310200',  @source_owner = N'dbo',   @source_object = N'AM310200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM310200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM310200]',   @del_cmd = N'CALL [sp_MSdel_dboAM310200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM310200]'  
GO
use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM310500',  @source_owner = N'dbo',   @source_object = N'AM310500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM310500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM310500]',   @del_cmd = N'CALL [sp_MSdel_dboAM310500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM310500]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM310700',  @source_owner = N'dbo',   @source_object = N'AM310700',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM310700]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM310700]',   @del_cmd = N'CALL [sp_MSdel_dboAM310700]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM310700]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311100',  @source_owner = N'dbo',   @source_object = N'AM311100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311100]',   @del_cmd = N'CALL [sp_MSdel_dboAM311100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311200',  @source_owner = N'dbo',   @source_object = N'AM311200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311200]',   @del_cmd = N'CALL [sp_MSdel_dboAM311200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311300',  @source_owner = N'dbo',   @source_object = N'AM311300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311300]',   @del_cmd = N'CALL [sp_MSdel_dboAM311300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311300]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311600',  @source_owner = N'dbo',   @source_object = N'AM311600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311600]',   @del_cmd = N'CALL [sp_MSdel_dboAM311600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311600]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311M00',  @source_owner = N'dbo',   @source_object = N'AM311M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM311M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311M00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311N00',  @source_owner = N'dbo',   @source_object = N'AM311N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM311N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311P00',  @source_owner = N'dbo',   @source_object = N'AM311P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM311P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311R00',  @source_owner = N'dbo',   @source_object = N'AM311R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM311R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM311S00',  @source_owner = N'dbo',   @source_object = N'AM311S00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM311S00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM311S00]',   @del_cmd = N'CALL [sp_MSdel_dboAM311S00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM311S00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312000',  @source_owner = N'dbo',   @source_object = N'AM312000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312000]',   @del_cmd = N'CALL [sp_MSdel_dboAM312000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312000]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312100',  @source_owner = N'dbo',   @source_object = N'AM312100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312100]',   @del_cmd = N'CALL [sp_MSdel_dboAM312100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312200',  @source_owner = N'dbo',   @source_object = N'AM312200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312200]',   @del_cmd = N'CALL [sp_MSdel_dboAM312200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312300',  @source_owner = N'dbo',   @source_object = N'AM312300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312300]',   @del_cmd = N'CALL [sp_MSdel_dboAM312300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312300]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312400',  @source_owner = N'dbo',   @source_object = N'AM312400',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312400]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312400]',   @del_cmd = N'CALL [sp_MSdel_dboAM312400]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312400]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312500',  @source_owner = N'dbo',   @source_object = N'AM312500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312500]',   @del_cmd = N'CALL [sp_MSdel_dboAM312500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312500]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312600',  @source_owner = N'dbo',   @source_object = N'AM312600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312600]',   @del_cmd = N'CALL [sp_MSdel_dboAM312600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312600]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312700',  @source_owner = N'dbo',   @source_object = N'AM312700',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312700]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312700]',   @del_cmd = N'CALL [sp_MSdel_dboAM312700]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312700]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312800',  @source_owner = N'dbo',   @source_object = N'AM312800',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312800]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312800]',   @del_cmd = N'CALL [sp_MSdel_dboAM312800]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312800]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312M00',  @source_owner = N'dbo',   @source_object = N'AM312M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM312M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312M00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312N00',  @source_owner = N'dbo',   @source_object = N'AM312N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM312N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312P00',  @source_owner = N'dbo',   @source_object = N'AM312P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM312P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312R00',  @source_owner = N'dbo',   @source_object = N'AM312R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM312R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM312S00',  @source_owner = N'dbo',   @source_object = N'AM312S00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM312S00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM312S00]',   @del_cmd = N'CALL [sp_MSdel_dboAM312S00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM312S00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313000',  @source_owner = N'dbo',   @source_object = N'AM313000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313000]',   @del_cmd = N'CALL [sp_MSdel_dboAM313000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313000]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313100',  @source_owner = N'dbo',   @source_object = N'AM313100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313100]',   @del_cmd = N'CALL [sp_MSdel_dboAM313100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313L00',  @source_owner = N'dbo',   @source_object = N'AM313L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM313L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313L00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313M00',  @source_owner = N'dbo',   @source_object = N'AM313M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM313M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313M00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313N00',  @source_owner = N'dbo',   @source_object = N'AM313N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM313N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313P00',  @source_owner = N'dbo',   @source_object = N'AM313P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM313P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM313R00',  @source_owner = N'dbo',   @source_object = N'AM313R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM313R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM313R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM313R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM313R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314200',  @source_owner = N'dbo',   @source_object = N'AM314200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314200]',   @del_cmd = N'CALL [sp_MSdel_dboAM314200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314500',  @source_owner = N'dbo',   @source_object = N'AM314500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314500]',   @del_cmd = N'CALL [sp_MSdel_dboAM314500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314500]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314600',  @source_owner = N'dbo',   @source_object = N'AM314600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314600]',   @del_cmd = N'CALL [sp_MSdel_dboAM314600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314600]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314800',  @source_owner = N'dbo',   @source_object = N'AM314800',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314800]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314800]',   @del_cmd = N'CALL [sp_MSdel_dboAM314800]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314800]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314900',  @source_owner = N'dbo',   @source_object = N'AM314900',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314900]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314900]',   @del_cmd = N'CALL [sp_MSdel_dboAM314900]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314900]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314L00',  @source_owner = N'dbo',   @source_object = N'AM314L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM314L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314L00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314M00',  @source_owner = N'dbo',   @source_object = N'AM314M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM314M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314M00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314N00',  @source_owner = N'dbo',   @source_object = N'AM314N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM314N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314P00',  @source_owner = N'dbo',   @source_object = N'AM314P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM314P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM314R00',  @source_owner = N'dbo',   @source_object = N'AM314R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM314R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM314R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM314R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM314R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315000',  @source_owner = N'dbo',   @source_object = N'AM315000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315000]',   @del_cmd = N'CALL [sp_MSdel_dboAM315000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315000]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315100',  @source_owner = N'dbo',   @source_object = N'AM315100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315100]',   @del_cmd = N'CALL [sp_MSdel_dboAM315100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315200',  @source_owner = N'dbo',   @source_object = N'AM315200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315200]',   @del_cmd = N'CALL [sp_MSdel_dboAM315200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315300',  @source_owner = N'dbo',   @source_object = N'AM315300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315300]',   @del_cmd = N'CALL [sp_MSdel_dboAM315300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315300]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315400',  @source_owner = N'dbo',   @source_object = N'AM315400',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315400]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315400]',   @del_cmd = N'CALL [sp_MSdel_dboAM315400]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315400]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315600',  @source_owner = N'dbo',   @source_object = N'AM315600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315600]',   @del_cmd = N'CALL [sp_MSdel_dboAM315600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315600]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315800',  @source_owner = N'dbo',   @source_object = N'AM315800',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315800]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315800]',   @del_cmd = N'CALL [sp_MSdel_dboAM315800]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315800]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315L00',  @source_owner = N'dbo',   @source_object = N'AM315L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM315L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315L00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315M00',  @source_owner = N'dbo',   @source_object = N'AM315M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM315M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315M00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315N00',  @source_owner = N'dbo',   @source_object = N'AM315N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM315N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315P00',  @source_owner = N'dbo',   @source_object = N'AM315P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM315P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM315R00',  @source_owner = N'dbo',   @source_object = N'AM315R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM315R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM315R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM315R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM315R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316000',  @source_owner = N'dbo',   @source_object = N'AM316000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316000]',   @del_cmd = N'CALL [sp_MSdel_dboAM316000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316000]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316100',  @source_owner = N'dbo',   @source_object = N'AM316100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316100]',   @del_cmd = N'CALL [sp_MSdel_dboAM316100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316200',  @source_owner = N'dbo',   @source_object = N'AM316200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316200]',   @del_cmd = N'CALL [sp_MSdel_dboAM316200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316300',  @source_owner = N'dbo',   @source_object = N'AM316300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316300]',   @del_cmd = N'CALL [sp_MSdel_dboAM316300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316300]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316400',  @source_owner = N'dbo',   @source_object = N'AM316400',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316400]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316400]',   @del_cmd = N'CALL [sp_MSdel_dboAM316400]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316400]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316500',  @source_owner = N'dbo',   @source_object = N'AM316500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316500]',   @del_cmd = N'CALL [sp_MSdel_dboAM316500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316500]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316600',  @source_owner = N'dbo',   @source_object = N'AM316600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316600]',   @del_cmd = N'CALL [sp_MSdel_dboAM316600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316600]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316700',  @source_owner = N'dbo',   @source_object = N'AM316700',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316700]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316700]',   @del_cmd = N'CALL [sp_MSdel_dboAM316700]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316700]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316900',  @source_owner = N'dbo',   @source_object = N'AM316900',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316900]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316900]',   @del_cmd = N'CALL [sp_MSdel_dboAM316900]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316900]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316L00',  @source_owner = N'dbo',   @source_object = N'AM316L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM316L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316L00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316M00',  @source_owner = N'dbo',   @source_object = N'AM316M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM316M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316M00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316N00',  @source_owner = N'dbo',   @source_object = N'AM316N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM316N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316P00',  @source_owner = N'dbo',   @source_object = N'AM316P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM316P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM316R00',  @source_owner = N'dbo',   @source_object = N'AM316R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM316R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM316R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM316R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM316R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317000',  @source_owner = N'dbo',   @source_object = N'AM317000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317000]',   @del_cmd = N'CALL [sp_MSdel_dboAM317000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317000]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317100',  @source_owner = N'dbo',   @source_object = N'AM317100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317100]',   @del_cmd = N'CALL [sp_MSdel_dboAM317100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317200',  @source_owner = N'dbo',   @source_object = N'AM317200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317200]',   @del_cmd = N'CALL [sp_MSdel_dboAM317200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317300',  @source_owner = N'dbo',   @source_object = N'AM317300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317300]',   @del_cmd = N'CALL [sp_MSdel_dboAM317300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317300]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317500',  @source_owner = N'dbo',   @source_object = N'AM317500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317500]',   @del_cmd = N'CALL [sp_MSdel_dboAM317500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317500]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317700',  @source_owner = N'dbo',   @source_object = N'AM317700',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317700]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317700]',   @del_cmd = N'CALL [sp_MSdel_dboAM317700]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317700]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317800',  @source_owner = N'dbo',   @source_object = N'AM317800',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317800]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317800]',   @del_cmd = N'CALL [sp_MSdel_dboAM317800]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317800]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317L00',  @source_owner = N'dbo',   @source_object = N'AM317L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM317L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317L00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317M00',  @source_owner = N'dbo',   @source_object = N'AM317M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM317M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317M00]'  GO
  use [scalaDB]  
 exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317N00',  @source_owner = N'dbo',   @source_object = N'AM317N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM317N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317P00',  @source_owner = N'dbo',   @source_object = N'AM317P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM317P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM317R00',  @source_owner = N'dbo',   @source_object = N'AM317R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM317R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM317R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM317R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM317R00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318000',  @source_owner = N'dbo',   @source_object = N'AM318000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318000]',   @del_cmd = N'CALL [sp_MSdel_dboAM318000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318000]'
  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318100',  @source_owner = N'dbo',   @source_object = N'AM318100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318100]',   @del_cmd = N'CALL [sp_MSdel_dboAM318100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318100]'
  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318300',  @source_owner = N'dbo',   @source_object = N'AM318300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318300]',   @del_cmd = N'CALL [sp_MSdel_dboAM318300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318300]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318400',  @source_owner = N'dbo',   @source_object = N'AM318400',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318400]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318400]',   @del_cmd = N'CALL [sp_MSdel_dboAM318400]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318400]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318500',  @source_owner = N'dbo',   @source_object = N'AM318500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318500]',   @del_cmd = N'CALL [sp_MSdel_dboAM318500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318500]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318800',  @source_owner = N'dbo',   @source_object = N'AM318800',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318800]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318800]',   @del_cmd = N'CALL [sp_MSdel_dboAM318800]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318800]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318900',  @source_owner = N'dbo',   @source_object = N'AM318900',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318900]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318900]',   @del_cmd = N'CALL [sp_MSdel_dboAM318900]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318900]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318L00',  @source_owner = N'dbo',   @source_object = N'AM318L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM318L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318L00]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318M00',  @source_owner = N'dbo',   @source_object = N'AM318M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM318M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318M00]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318N00',  @source_owner = N'dbo',   @source_object = N'AM318N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM318N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318N00]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318P00',  @source_owner = N'dbo',   @source_object = N'AM318P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM318P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318P00]' 
 GO
  use [scalaDB]  
 exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM318R00',  @source_owner = N'dbo',   @source_object = N'AM318R00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM318R00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM318R00]',   @del_cmd = N'CALL [sp_MSdel_dboAM318R00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM318R00]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319000',  @source_owner = N'dbo',   @source_object = N'AM319000',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319000]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319000]',   @del_cmd = N'CALL [sp_MSdel_dboAM319000]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319000]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319100',  @source_owner = N'dbo',   @source_object = N'AM319100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319100]',   @del_cmd = N'CALL [sp_MSdel_dboAM319100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319100]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319200',  @source_owner = N'dbo',   @source_object = N'AM319200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319200]',   @del_cmd = N'CALL [sp_MSdel_dboAM319200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319200]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319300',  @source_owner = N'dbo',   @source_object = N'AM319300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319300]',   @del_cmd = N'CALL [sp_MSdel_dboAM319300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319300]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319600',  @source_owner = N'dbo',   @source_object = N'AM319600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319600]',   @del_cmd = N'CALL [sp_MSdel_dboAM319600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319600]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319700',  @source_owner = N'dbo',   @source_object = N'AM319700',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319700]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319700]',   @del_cmd = N'CALL [sp_MSdel_dboAM319700]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319700]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319900',  @source_owner = N'dbo',   @source_object = N'AM319900',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319900]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319900]',   @del_cmd = N'CALL [sp_MSdel_dboAM319900]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319900]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319L00',  @source_owner = N'dbo',   @source_object = N'AM319L00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319L00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319L00]',   @del_cmd = N'CALL [sp_MSdel_dboAM319L00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319L00]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319M00',  @source_owner = N'dbo',   @source_object = N'AM319M00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319M00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319M00]',   @del_cmd = N'CALL [sp_MSdel_dboAM319M00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319M00]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319N00',  @source_owner = N'dbo',   @source_object = N'AM319N00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319N00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319N00]',   @del_cmd = N'CALL [sp_MSdel_dboAM319N00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319N00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM319P00',  @source_owner = N'dbo',   @source_object = N'AM319P00',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM319P00]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM319P00]',   @del_cmd = N'CALL [sp_MSdel_dboAM319P00]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM319P00]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V100',  @source_owner = N'dbo',   @source_object = N'AM31V100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V100]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V200',  @source_owner = N'dbo',   @source_object = N'AM31V200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V200]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V200]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V300',  @source_owner = N'dbo',   @source_object = N'AM31V300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V300]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V300]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V500',  @source_owner = N'dbo',   @source_object = N'AM31V500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V500]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V500]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V600',  @source_owner = N'dbo',   @source_object = N'AM31V600',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V600]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V600]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V600]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V600]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V800',  @source_owner = N'dbo',   @source_object = N'AM31V800',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V800]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V800]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V800]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V800]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31V900',  @source_owner = N'dbo',   @source_object = N'AM31V900',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31V900]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31V900]',   @del_cmd = N'CALL [sp_MSdel_dboAM31V900]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31V900]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31W100',  @source_owner = N'dbo',   @source_object = N'AM31W100',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31W100]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31W100]',   @del_cmd = N'CALL [sp_MSdel_dboAM31W100]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31W100]'  GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31W200',  @source_owner = N'dbo',   @source_object = N'AM31W200',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31W200]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31W200]',   @del_cmd = N'CALL [sp_MSdel_dboAM31W200]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31W200]' 
 GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31W300',  @source_owner = N'dbo',   @source_object = N'AM31W300',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31W300]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31W300]',   @del_cmd = N'CALL [sp_MSdel_dboAM31W300]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31W300]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31W400',  @source_owner = N'dbo',   @source_object = N'AM31W400',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31W400]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31W400]',   @del_cmd = N'CALL [sp_MSdel_dboAM31W400]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31W400]'  
GO
  use [scalaDB]   
exec sp_addarticle @publication = N'PublicationScalaAM31',   @article = N'AM31W500',  @source_owner = N'dbo',   @source_object = N'AM31W500',   @type = N'logbased',   @description = N'',   @creation_script = N'',  @pre_creation_cmd = N'drop', @schema_option = 0x000000000803509F,   @identityrangemanagementoption = N'none',   @destination_table = N'[AM31W500]',   @destination_owner = N'dbo', @status = 24,   @vertical_partition = N'false',   @ins_cmd = N'CALL [sp_MSins_dboAM31W500]',   @del_cmd = N'CALL [sp_MSdel_dboAM31W500]',   @upd_cmd = N'SCALL [sp_MSupd_dboAM31W500]'  
GO

-- Adding the transactional subscriptions
--use [scalaDB]
--exec sp_addsubscription @publication = N'PublicationScalaAM31', @subscriber = N'VM-TAL-SAP01', @destination_db = N'scalaDB', @subscription_type = N'Push', @sync_type = N'replication support only', @article = N'all', @update_mode = N'read only', @subscriber_type = 0
--exec sp_addpushsubscription_agent @publication = N'PublicationScalaAM31', @subscriber = N'VM-TAL-SAP01', @subscriber_db = N'scalaDB', @job_login = null, @job_password = null, @subscriber_security_mode = 1, @frequency_type = 64, @frequency_interval = 1, @frequency_relative_interval = 1, @frequency_recurrence_factor = 0, @frequency_subday = 4, @frequency_subday_interval = 5, @active_start_time_of_day = 0, @active_end_time_of_day = 235959, @active_start_date = 0, @active_end_date = 0, @dts_package_location = N'Distributor'
--GO

